//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public int receipt_id { get; set; }
        public int ingredient_id { get; set; }
        public double quantity { get; set; }
    
        public virtual ProductsStored ProductsStored { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
