//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int product_id { get; set; }
        public System.DateTime period_start { get; set; }
        public decimal price1 { get; set; }
    
        public virtual ProductsSold ProductsSold { get; set; }
    }
}
