//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class productSimple
    {
        public int id { get; set; }
        public string name { get; set; }
        public string category_name { get; set; }
        public Nullable<bool> sold { get; set; }
        public Nullable<bool> stored { get; set; }
    }
}
