//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int id { get; set; }
        public string unit_name { get; set; }
        public double convert_factor { get; set; }
        public Nullable<int> unit_type { get; set; }
    
        public virtual UnitType UnitType { get; set; }
    }
}
